services:
  backend:
    build: .
    image: online-food-ordering
    container_name: online-food-ordering-backend
    ports:
      - "8080:8080"
    depends_on:
      - online-food-ordering-db
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://online-food-ordering-db:3306/foodappdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    restart: always

  online-food-ordering-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: foodappdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: