services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: foodappdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: