spring:
    datasource:
      url: 'jdbc:mysql://${MYSQL_HOST}:3306/foodappdb'
      username: '${DB_USERNAME}'
      password: '${DB_PASSWORD}'
jwt:
  secret:
    key: '${JWT_SECRET_KEY}'
stripe:
  api:
    key: '${STRIPE_API_KEY}'