name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/online-food-ordering:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/online-food-ordering:latest

      - name: Set up SSH key
        run: |
          echo "${{ secrets.GCP_SSH_KEY }}" > private-key.pem
          chmod 600 private-key.pem

      - name: SSH into GCP VM and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i private-key.pem ${{ secrets.GCP_VM_USERNAME }}@${{ secrets.GCP_VM_IP }} << 'EOF'
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/online-food-ordering:latest
            docker stop online-food-ordering || true
            docker rm online-food-ordering || true
            docker run -d -p 8080:8080 --name online-food-ordering ${{ secrets.DOCKERHUB_USERNAME }}/online-food-ordering:latest
          EOF
